name: Convert Optimus2502.bin to PGN

on:
  workflow_dispatch:            # run manually
  push:                          # or automatically when the book changes
    paths:
      - Optimus2502.bin

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ check out the repo so the .bin is available
    - uses: actions/checkout@v4

    # 2 ▸ lightweight Python setup
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3 ▸ install pure-Python dependency
    - name: Install python-chess
      run: pip install --quiet 'chess>=1.10.0'

    # 4 ▸ inline script: dump EVERY book line to PGN (no ply cap, no TypeError)
    - name: Convert .bin → .pgn
      run: |
        python - <<'PY'
        import chess, chess.polyglot, chess.pgn, pathlib, sys

        BIN = pathlib.Path("Optimus2502.bin")
        PGN = pathlib.Path("Optimus2502.pgn")

        if not BIN.exists():
            sys.exit(f"❌ {BIN} not found. Make sure the file is in the repo root.")

        def walk(board, reader, line):
            """Depth-first traversal of the Polyglot move tree."""
            entries = list(reader.find_all(board))
            if not entries:               # leaf → output this line
                yield line
            else:
                for entry in entries:
                    move = entry.move     # <-- fixed: .move is an attribute, not a method
                    nxt = board.copy(stack=False)
                    nxt.push(move)
                    yield from walk(nxt, reader, line + [move])

        with chess.polyglot.open_reader(str(BIN)) as book, PGN.open("w", encoding="utf-8") as out:
            for moves in walk(chess.Board(), book, []):
                game = chess.pgn.Game()
                node = game
                for mv in moves:
                    node = node.add_variation(mv)
                print(game, file=out, end="\n\n")

        print(f"✅ Finished: wrote {PGN} with all book lines.")
        PY

    # 5 ▸ upload result using the supported v4 action
    - uses: actions/upload-artifact@v4
      with:
        name: Optimus2502.pgn
        path: Optimus2502.pgn
