name: Evaluate Book

on:
  workflow_dispatch:

jobs:
  test_book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install python-chess
        run: pip install chess

      - name: Download Stockfish
        run: |
          mkdir sf
          wget https://github.com/official-stockfish/Stockfish/releases/download/sf_17/stockfish-ubuntu-x86-64-avx2 -O ./sf/stockfish
          chmod +x ./sf/stockfish

      - name: Upload your Optimus book
        run: |
          mkdir books
          curl -LJO "https://github.com/${{ github.repository }}/raw/main/Optimus2502.bin"
          mv Optimus2502.bin books/book.bin

      - name: Evaluate Book Games
        run: python3 filter_bad_games.py

      - name: Upload PGN of bad games
        uses: actions/upload-artifact@v4
        with:
          name: bad_games
          path: bad_games.pgn
