name: Build and Convert Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool

    - name: Clone and build Polyglot
      run: |
        git clone https://github.com/ddugovic/polyglot.git "$HOME/polyglot"
        cd "$HOME/polyglot"
        autoreconf -fi
        ./configure
        make

    - name: Convert Optimus2502.bin to PGN
      run: |
        mkdir -p converted
        "$HOME/polyglot/polyglot" \
          --binbook Optimus2502.bin \
          --pgnout converted/Optimus2502.pgn \
          --reverse

    - name: Upload PGN file
      uses: actions/upload-artifact@v4
      with:
        name: Optimus2502.pgn
        path: converted/Optimus2502.pgn
