name: Convert Optimus2502.bin to PGN

on:
  workflow_dispatch:          # manual trigger
  push:                       # auto-run when the book changes
    paths:
      - Optimus2502.bin

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install python-chess
      run: pip install --quiet 'chess>=1.10.0'

    - name: Dump book to PGN (cycle-safe, no recursion)
      run: |
        python - <<'PY'
        import chess, chess.polyglot, chess.pgn, pathlib, sys, collections

        BIN = pathlib.Path("Optimus2502.bin")
        OUT = pathlib.Path("Optimus2502.pgn")

        if not BIN.exists():
            sys.exit("❌ Optimus2502.bin not found in repo root.")

        reader = chess.polyglot.open_reader(str(BIN))
        root   = chess.Board()

        # stack item: (board, move_list, seen_hashes)
        Item = collections.namedtuple("Item", "board line seen")
        stack = [Item(root, [], {root._transposition_key})]   # ← use the real attribute

        with OUT.open("w", encoding="utf-8") as pgn:
            while stack:
                board, line, seen = stack.pop()

                moves = list(reader.find_all(board))
                if not moves:                         # leaf → emit PGN game
                    game = chess.pgn.Game()
                    node = game
                    for mv in line:
                        node = node.add_variation(mv)
                    print(game, file=pgn, end="\n\n")
                    continue

                for entry in reversed(moves):         # preserve order
                    mv = entry.move
                    board.push(mv)
                    key = board._transposition_key    # ✔ cycle check
                    if key not in seen:
                        stack.append(Item(board.copy(stack=False),
                                           line + [mv],
                                           seen | {key}))
                    board.pop()

        reader.close()
        print(f"✅ Finished – complete PGN saved to {OUT}")
        PY

    - name: Upload PGN
      uses: actions/upload-artifact@v4
      with:
        name: Optimus2502.pgn
        path: Optimus2502.pgn
