name: Evaluate Book

on:
  workflow_dispatch:

jobs:
  test_book:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # 3. python-chess
      - name: Install python-chess
        run: pip install chess

      # 4. Stockfish from Ubuntu repo
      - name: Install Stockfish
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish
          ln -s "$(which stockfish)" ./stockfish   # makes ./stockfish path for script

      # 5. Check the book is present
      - name: Ensure Optimus book exists
        run: |
          test -f Optimus2502.bin || { echo "Optimus2502.bin missing!"; exit 1; }

      # 6. Run the evaluation script
      - name: Evaluate Book (find bad games)
        run: python3 filter_bad_games.py

      # 7. Upload the bad-game PGN
      - name: Upload PGN of bad games
        uses: actions/upload-artifact@v4
        with:
          name: bad_games
          path: bad_games.pgn
