name: Export PGN from Book

on:
  workflow_dispatch:

jobs:
  export-pgn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install python-chess
        run: pip install chess

      - name: Create PGN export script
        run: |
          cat > export_pgn_from_book.py << 'EOF'
          import chess
          import chess.polyglot
          import chess.pgn
          import pathlib
          import sys

          BIN = pathlib.Path("Optimus2502.bin")
          PGN = pathlib.Path("Optimus2502.pgn")
          MAX_DEPTH = 12  # Max number of half-moves (6 full moves)

          if not BIN.is_file():
              sys.exit(f"❌ {BIN} not found in repo root.")

          with chess.polyglot.open_reader(str(BIN)) as reader, PGN.open("w", encoding="utf-8") as out:
              root = chess.Board()
              stack = [(root, [])]

              while stack:
                  board, line = stack.pop()

                  if len(line) >= MAX_DEPTH or not list(reader.find_all(board)):
                      game = chess.pgn.Game()
                      node = game
                      for mv in line:
                          node = node.add_variation(mv)
                      print(game, file=out, end="\n\n")
                      continue

                  for entry in list(reader.find_all(board))[::-1]:
                      mv = entry.move
                      board.push(mv)
                      stack.append((board.copy(stack=False), line + [mv]))
                      board.pop()

          print(f"✅ Wrote PGNs (up to {MAX_DEPTH} plies) to {PGN}")
          EOF

      - name: Run PGN extraction
        run: python export_pgn_from_book.py

      - name: Upload PGN artifact
        uses: actions/upload-artifact@v4
        with:
          name: optimus2502-pgn
          path: Optimus2502.pgn
