name: Generate Bad Book from Optimus2502

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-pip stockfish

      - name: Download Stockfish
        run: |
          wget https://stockfishchess.org/files/stockfish-ubuntu-x86-64-avx2.zip
          unzip stockfish-ubuntu-x86-64-avx2.zip
          mv stockfish/* ./sf
          chmod +x ./sf

      - name: Run filter script
        run: python3 filter_bad_games.py

      - name: Upload result book
        uses: actions/upload-artifact@v4
        with:
          name: badbook
          path: badbook.bin
