name: Evaluate Opening Book

on:
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Stockfish
        run: |
          curl -L -o stockfish.zip https://stockfishchess.org/files/stockfish_16.1_linux_x64_avx2.zip
          unzip -j stockfish.zip
          chmod +x stockfish

      - name: Download Polyglot
        run: sudo apt-get install -y polyglot

      - name: Install cutechess-cli
        run: sudo apt-get install -y cutechess-cli

      - name: Run matches with cutechess-cli
        run: |
          cutechess-cli \
            -engine name=SFBook cmd=polyglot dir=. option="Engine ./stockfish" option="BookFile Optimus2502.bin" \
            -engine name=SFPlain cmd=./stockfish \
            -each tc=40/0.05 \
            -games 50 \
            -pgnout all_games.pgn

      - name: Filter bad games from PGN
        run: python3 filter_bad_games.py

      - name: Upload bad PGN file
        uses: actions/upload-artifact@v4
        with:
          name: bad-pgn
          path: bad_games.pgn
