# .github/workflows/bin-to-pgn.yml
name: Dump Optimus2502.bin to PGN

on:
  push:
    paths:
      - Optimus2502.bin        # run when the book itself changes
  workflow_dispatch:           # …or when you press “Run workflow”

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ check out your repo
    - uses: actions/checkout@v4

    # 2 ▸ install compiler tool-chain
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

    # 3 ▸ clone Polyglot **(note: no /src folder any more)**
    - name: Clone Polyglot source
      run: |
        git clone --depth 1 https://github.com/ddugovic/polyglot.git "$HOME/polyglot"

    # 4 ▸ build in the project root, not $HOME/polyglot/src
    - name: Build Polyglot
      run: |
        make -j"$(nproc)" -C "$HOME/polyglot"

    # 5 ▸ dump White and Black lines, then join them
    - name: Convert .bin to .pgn
      run: |
        BIN_IN="Optimus2502.bin"
        PGN_OUT="Optimus2502.pgn"
        "$HOME/polyglot/polyglot" book dump -bin "$BIN_IN" -color white -out white.pgn
        "$HOME/polyglot/polyglot" book dump -bin "$BIN_IN" -color black -out black.pgn
        cat white.pgn black.pgn > "$PGN_OUT"

    # 6 ▸ upload the PGN as a workflow artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Optimus2502_PGN
        path: Optimus2502.pgn
