name: Evaluate Book

on:
  workflow_dispatch:

jobs:
  test_book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: pip install chess

      - name: Install Stockfish
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish
          ln -s $(which stockfish) ./stockfish   # ./stockfish path for script

      - name: Place Optimus book
        run: |
          mkdir -p books
          cp Optimus2502.bin books/book.bin      # file already in repo

      - name: Evaluate Book Games
        run: python3 filter_bad_games.py         # your script name

      - name: Upload PGN of bad games
        uses: actions/upload-artifact@v4
        with:
          name: bad_games
          path: bad_games.pgn
